import Head from 'next/head';
import Image from 'next/image';
import { Button, Container } from 'react-bootstrap';
import styles from '../styles/Home.module.css';
import HomePage from '../component/home';
import styled from 'styled-components';

export default function Home() {
  return (
    <AppContainer>
      <Head>
        <title>Challenge App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage></HomePage>
    </AppContainer>
  );
}
const AppContainer = styled(Container)`
  padding-top: 30px;
`;
